import type { AuthUser } from "@/domains/auth/types";
import { buildProjectIssueId } from "@/domains/task/identifiers";
import type { FileRecord, TaskRecord } from "@/domains/task/types";

export const previewAuthUser: AuthUser = {
  id: "preview-user",
  email: "preview@local",
  displayName: "Preview User",
  name: "Preview User",
  role: "admin",
  accessStatus: "active",
};

export const previewProjectName = "Preview Project";

export const previewSystemMode = {
  backendMode: "local",
  dataMode: "preview",
  uploadMode: "mock-storage",
  hasSupabase: false,
  hasFirebaseProjectId: false,
};

const today = new Date();
const isoDate = (offsetDays: number) => {
  const next = new Date(today);
  next.setDate(next.getDate() + offsetDays);
  return next.toISOString().slice(0, 10);
};

const isoStamp = (offsetDays: number) => {
  const next = new Date(today);
  next.setDate(next.getDate() + offsetDays);
  return next.toISOString();
};

function history(status: TaskRecord["status"], offsetDays: number) {
  return `${isoStamp(offsetDays)} - ${status}`;
}

export const previewTasks: TaskRecord[] = [
  {
    id: "task-100",
    projectId: "preview-project",
    taskNumber: 101,
    actionId: 101,
    issueId: buildProjectIssueId(previewProjectName, 101),
    parentTaskId: null,
    rootTaskId: "task-100",
    depth: 0,
    siblingOrder: 0,
    dueDate: isoDate(-1),
    workType: "revision",
    coordinationScope: "Architecture + UX",
    ownerDiscipline: "Design",
    requestedBy: "PM",
    relatedDisciplines: "Brand, Content",
    assignee: "Mina",
    assigneeProfileId: null,
    issueTitle: "Landing hero refinement",
    reviewedAt: isoDate(-2),
    createdAt: isoDate(-7),
    createdBy: "preview-user",
    isDaily: true,
    locationRef: "L1-Hero",
    calendarLinked: true,
    issueDetailNote: "Refine the hero section copy and spacing.",
    status: "new",
    statusHistory: history("new", -7),
    decision: "",
    completedAt: null,
    version: 3,
    updatedAt: isoStamp(-1),
    updatedBy: "preview-user",
    deletedAt: null,
    purgedAt: null,
  },
  {
    id: "task-101",
    projectId: "preview-project",
    taskNumber: 102,
    actionId: 102,
    issueId: buildProjectIssueId(previewProjectName, 102),
    parentTaskId: null,
    rootTaskId: "task-101",
    depth: 0,
    siblingOrder: 1,
    dueDate: isoDate(1),
    workType: "coordination",
    coordinationScope: "UI",
    ownerDiscipline: "Frontend",
    requestedBy: "Lead",
    relatedDisciplines: "QA, UX",
    assignee: "Jin",
    assigneeProfileId: null,
    issueTitle: "Board filter UI polish",
    reviewedAt: isoDate(0),
    createdAt: isoDate(-6),
    createdBy: "preview-user",
    isDaily: true,
    locationRef: "Board > Filters",
    calendarLinked: true,
    issueDetailNote: "Adjust spacing and interaction hints for board filters.",
    status: "in_review",
    statusHistory: `${history("new", -6)}\n${history("in_review", -5)}`,
    decision: "",
    completedAt: null,
    version: 5,
    updatedAt: isoStamp(-1),
    updatedBy: "preview-user",
    deletedAt: null,
    purgedAt: null,
  },
  {
    id: "task-102",
    projectId: "preview-project",
    taskNumber: 103,
    actionId: 103,
    issueId: buildProjectIssueId(previewProjectName, 103),
    parentTaskId: "task-101",
    rootTaskId: "task-101",
    depth: 1,
    siblingOrder: 0,
    dueDate: isoDate(2),
    workType: "review",
    coordinationScope: "Responsive UX",
    ownerDiscipline: "Frontend",
    requestedBy: "Lead",
    relatedDisciplines: "QA",
    assignee: "Jin",
    assigneeProfileId: null,
    issueTitle: "Mobile empty-state treatment",
    reviewedAt: "",
    createdAt: isoDate(-5),
    createdBy: "preview-user",
    isDaily: true,
    locationRef: "Mobile > Empty states",
    calendarLinked: false,
    issueDetailNote: "Tune mobile empty states for daily and board views.",
    status: "in_discussion",
    statusHistory: `${history("in_review", -5)}\n${history("in_discussion", -4)}`,
    decision: "",
    completedAt: null,
    version: 2,
    updatedAt: isoStamp(-1),
    updatedBy: "preview-user",
    deletedAt: null,
    purgedAt: null,
  },
  {
    id: "task-107",
    projectId: "preview-project",
    taskNumber: 108,
    actionId: 108,
    issueId: buildProjectIssueId(previewProjectName, 108),
    parentTaskId: "task-101",
    rootTaskId: "task-101",
    depth: 1,
    siblingOrder: 2,
    dueDate: isoDate(3),
    workType: "reply",
    coordinationScope: "QA Follow-up",
    ownerDiscipline: "Frontend",
    requestedBy: "Lead",
    relatedDisciplines: "QA",
    assignee: "Jin",
    assigneeProfileId: null,
    issueTitle: "Keyboard hint cleanup",
    reviewedAt: "",
    createdAt: isoDate(-3),
    createdBy: "preview-user",
    isDaily: true,
    locationRef: "Daily > Mobile states",
    calendarLinked: false,
    issueDetailNote: "Refine keyboard interaction hint copy after QA review.",
    status: "in_review",
    statusHistory: history("in_review", -3),
    decision: "",
    completedAt: null,
    version: 1,
    updatedAt: isoStamp(-1),
    updatedBy: "preview-user",
    deletedAt: null,
    purgedAt: null,
  },
  {
    id: "task-106",
    projectId: "preview-project",
    taskNumber: 107,
    actionId: 107,
    issueId: buildProjectIssueId(previewProjectName, 107),
    parentTaskId: "task-101",
    rootTaskId: "task-101",
    depth: 1,
    siblingOrder: 1,
    dueDate: isoDate(2),
    workType: "request",
    coordinationScope: "Tablet UX",
    ownerDiscipline: "Frontend",
    requestedBy: "Lead",
    relatedDisciplines: "QA, UX",
    assignee: "Jin",
    assigneeProfileId: null,
    issueTitle: "Tablet spacing follow-up",
    reviewedAt: "",
    createdAt: isoDate(-4),
    createdBy: "preview-user",
    isDaily: true,
    locationRef: "Board > Filters",
    calendarLinked: false,
    issueDetailNote: "Follow up on tablet spacing after the first pass lands.",
    status: "new",
    statusHistory: history("new", -4),
    decision: "",
    completedAt: null,
    version: 1,
    updatedAt: isoStamp(-1),
    updatedBy: "preview-user",
    deletedAt: null,
    purgedAt: null,
  },
  {
    id: "task-103",
    projectId: "preview-project",
    taskNumber: 104,
    actionId: 104,
    issueId: buildProjectIssueId(previewProjectName, 104),
    parentTaskId: null,
    rootTaskId: "task-103",
    depth: 0,
    siblingOrder: 2,
    dueDate: isoDate(4),
    workType: "confirmation",
    coordinationScope: "Messaging",
    ownerDiscipline: "Backend",
    requestedBy: "Architect",
    relatedDisciplines: "Frontend",
    assignee: "Hana",
    assigneeProfileId: null,
    issueTitle: "Conflict message copy",
    reviewedAt: isoDate(-1),
    createdAt: isoDate(-4),
    createdBy: "preview-user",
    isDaily: false,
    locationRef: "Tasks API",
    calendarLinked: false,
    issueDetailNote: "Update the 409 conflict recovery message for clarity.",
    status: "blocked",
    statusHistory: `${history("in_review", -4)}\n${history("blocked", -2)}`,
    decision: "Waiting for final wording decision.",
    completedAt: null,
    version: 4,
    updatedAt: isoStamp(-1),
    updatedBy: "preview-user",
    deletedAt: null,
    purgedAt: null,
  },
  {
    id: "task-104",
    projectId: "preview-project",
    taskNumber: 105,
    actionId: 105,
    issueId: buildProjectIssueId(previewProjectName, 105),
    parentTaskId: null,
    rootTaskId: "task-104",
    depth: 0,
    siblingOrder: 3,
    dueDate: isoDate(-3),
    workType: "record",
    coordinationScope: "Rollout",
    ownerDiscipline: "Operations",
    requestedBy: "Ops",
    relatedDisciplines: "Product, Engineering",
    assignee: "Alex",
    assigneeProfileId: null,
    issueTitle: "Cutover checklist review",
    reviewedAt: isoDate(-4),
    createdAt: isoDate(-10),
    createdBy: "preview-user",
    isDaily: false,
    locationRef: "Migration Runbook",
    calendarLinked: true,
    issueDetailNote: "Review migration and cutover steps before rollout.",
    status: "done",
    statusHistory: `${history("in_discussion", -9)}\n${history("done", -3)}`,
    decision: "Reviewed with the team.",
    completedAt: isoStamp(-3),
    version: 6,
    updatedAt: isoStamp(-3),
    updatedBy: "preview-user",
    deletedAt: null,
    purgedAt: null,
  },
  {
    id: "task-105",
    projectId: "preview-project",
    taskNumber: 106,
    actionId: 106,
    issueId: buildProjectIssueId(previewProjectName, 106),
    parentTaskId: null,
    rootTaskId: "task-105",
    depth: 0,
    siblingOrder: 4,
    dueDate: isoDate(-8),
    workType: "record",
    coordinationScope: "Reference",
    ownerDiscipline: "Design",
    requestedBy: "PM",
    relatedDisciplines: "",
    assignee: "Mina",
    assigneeProfileId: null,
    issueTitle: "Old trash sample",
    reviewedAt: "",
    createdAt: isoDate(-14),
    createdBy: "preview-user",
    isDaily: false,
    locationRef: "Trash",
    calendarLinked: false,
    issueDetailNote: "Sample deleted task for preview mode.",
    status: "done",
    statusHistory: history("done", -8),
    decision: "",
    completedAt: isoStamp(-8),
    version: 1,
    updatedAt: isoStamp(-8),
    updatedBy: "preview-user",
    deletedAt: "2026-03-09T09:00:00.000Z",
    purgedAt: null,
  },
];

export const previewFiles: FileRecord[] = [
  {
    id: "file-100",
    taskId: "task-101",
    projectId: "preview-project",
    fileGroupId: "group-100",
    originalName: "board-filter-spec.pdf",
    mimeType: "application/pdf",
    sizeBytes: 428392,
    storageBucket: "preview-bucket",
    objectPath: "preview/board-filter-spec.pdf",
    version: 2,
    versionNumber: 2,
    versionLabel: "v2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    uploadedBy: "preview-user",
    deletedAt: null,
    purgedAt: null,
  },
  {
    id: "file-101",
    taskId: "task-102",
    projectId: "preview-project",
    fileGroupId: "group-101",
    originalName: "mobile-empty-state.png",
    mimeType: "image/png",
    sizeBytes: 182394,
    storageBucket: "preview-bucket",
    objectPath: "preview/mobile-empty-state.png",
    version: 1,
    versionNumber: 1,
    versionLabel: "v1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    uploadedBy: "preview-user",
    deletedAt: null,
    purgedAt: null,
  },
  {
    id: "file-102",
    taskId: "task-105",
    projectId: "preview-project",
    fileGroupId: "group-102",
    originalName: "archived-note.txt",
    mimeType: "text/plain",
    sizeBytes: 1204,
    storageBucket: "preview-bucket",
    objectPath: "preview/archived-note.txt",
    version: 1,
    versionNumber: 1,
    versionLabel: "v1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    uploadedBy: "preview-user",
    deletedAt: "2026-03-10T15:00:00.000Z",
    purgedAt: null,
  },
];
