import type { AuthUser } from "@/domains/auth/types";
import type { FileRecord, TaskRecord } from "@/domains/task/types";

export const previewAuthUser: AuthUser = {
  id: "preview-user",
  email: "preview@local",
  displayName: "Preview User",
  name: "Preview User",
  role: "admin",
};

export const previewProjectName = "Preview Project";

export const previewSystemMode = {
  dataMode: "preview",
  uploadMode: "mock-storage",
  hasSupabase: false,
  hasFirebaseProjectId: false,
};

const today = new Date();
const isoDate = (offsetDays: number) => {
  const next = new Date(today);
  next.setDate(next.getDate() + offsetDays);
  return next.toISOString().slice(0, 10);
};

export const previewTasks: TaskRecord[] = [
  {
    id: "task-100",
    projectId: "preview-project",
    taskNumber: 101,
    parentTaskId: null,
    rootTaskId: "task-100",
    depth: 0,
    siblingOrder: 0,
    dueDate: isoDate(-1),
    category: "Design",
    requester: "PM",
    assignee: "Mina",
    title: "Landing hero refinement",
    createdAt: isoDate(-7),
    createdBy: "preview-user",
    isDaily: true,
    description: "Refine the hero section copy and spacing.",
    status: "waiting",
    progressNote: "",
    conclusion: "",
    fileMemo: "Need updated brand tone samples.",
    version: 3,
    updatedAt: new Date().toISOString(),
    updatedBy: "preview-user",
    deletedAt: null,
  },
  {
    id: "task-101",
    projectId: "preview-project",
    taskNumber: 102,
    parentTaskId: null,
    rootTaskId: "task-101",
    depth: 0,
    siblingOrder: 1,
    dueDate: isoDate(1),
    category: "Frontend",
    requester: "Lead",
    assignee: "Jin",
    title: "Board filter UI polish",
    createdAt: isoDate(-6),
    createdBy: "preview-user",
    isDaily: true,
    description: "Adjust spacing and interaction hints for board filters.",
    status: "todo",
    progressNote: "Waiting for final spacing call.",
    conclusion: "",
    fileMemo: "",
    version: 5,
    updatedAt: new Date().toISOString(),
    updatedBy: "preview-user",
    deletedAt: null,
  },
  {
    id: "task-102",
    projectId: "preview-project",
    taskNumber: 103,
    parentTaskId: "task-101",
    rootTaskId: "task-101",
    depth: 1,
    siblingOrder: 0,
    dueDate: isoDate(2),
    category: "Frontend",
    requester: "Lead",
    assignee: "Jin",
    title: "Mobile empty-state treatment",
    createdAt: isoDate(-5),
    createdBy: "preview-user",
    isDaily: true,
    description: "Tune mobile empty states for daily and board views.",
    status: "in_progress",
    progressNote: "Component styles are in review.",
    conclusion: "",
    fileMemo: "",
    version: 2,
    updatedAt: new Date().toISOString(),
    updatedBy: "preview-user",
    deletedAt: null,
  },
  {
    id: "task-103",
    projectId: "preview-project",
    taskNumber: 104,
    parentTaskId: null,
    rootTaskId: "task-103",
    depth: 0,
    siblingOrder: 2,
    dueDate: isoDate(4),
    category: "API",
    requester: "Architect",
    assignee: "Hana",
    title: "Conflict message copy",
    createdAt: isoDate(-4),
    createdBy: "preview-user",
    isDaily: false,
    description: "Update the 409 conflict recovery message for clarity.",
    status: "blocked",
    progressNote: "Need Korean wording decision.",
    conclusion: "",
    fileMemo: "",
    version: 4,
    updatedAt: new Date().toISOString(),
    updatedBy: "preview-user",
    deletedAt: null,
  },
  {
    id: "task-104",
    projectId: "preview-project",
    taskNumber: 105,
    parentTaskId: null,
    rootTaskId: "task-104",
    depth: 0,
    siblingOrder: 3,
    dueDate: isoDate(-3),
    category: "Docs",
    requester: "Ops",
    assignee: "Alex",
    title: "Cutover checklist review",
    createdAt: isoDate(-10),
    createdBy: "preview-user",
    isDaily: false,
    description: "Review migration and cutover steps before rollout.",
    status: "done",
    progressNote: "",
    conclusion: "Reviewed with the team.",
    fileMemo: "Checklist approved.",
    version: 6,
    updatedAt: new Date().toISOString(),
    updatedBy: "preview-user",
    deletedAt: null,
  },
  {
    id: "task-105",
    projectId: "preview-project",
    taskNumber: 106,
    parentTaskId: null,
    rootTaskId: "task-105",
    depth: 0,
    siblingOrder: 4,
    dueDate: isoDate(-8),
    category: "Archive",
    requester: "PM",
    assignee: "Mina",
    title: "Old trash sample",
    createdAt: isoDate(-14),
    createdBy: "preview-user",
    isDaily: false,
    description: "Sample deleted task for preview mode.",
    status: "done",
    progressNote: "",
    conclusion: "",
    fileMemo: "",
    version: 1,
    updatedAt: new Date().toISOString(),
    updatedBy: "preview-user",
    deletedAt: "2026-03-09T09:00:00.000Z",
  },
];

export const previewFiles: FileRecord[] = [
  {
    id: "file-100",
    taskId: "task-101",
    projectId: "preview-project",
    fileGroupId: "group-100",
    originalName: "board-filter-spec.pdf",
    mimeType: "application/pdf",
    sizeBytes: 428392,
    storageBucket: "preview-bucket",
    objectPath: "preview/board-filter-spec.pdf",
    version: 2,
    versionNumber: 2,
    versionLabel: "v2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    uploadedBy: "preview-user",
    deletedAt: null,
    downloadUrl: null,
  },
  {
    id: "file-101",
    taskId: "task-102",
    projectId: "preview-project",
    fileGroupId: "group-101",
    originalName: "mobile-empty-state.png",
    mimeType: "image/png",
    sizeBytes: 182394,
    storageBucket: "preview-bucket",
    objectPath: "preview/mobile-empty-state.png",
    version: 1,
    versionNumber: 1,
    versionLabel: "v1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    uploadedBy: "preview-user",
    deletedAt: null,
    downloadUrl: null,
  },
  {
    id: "file-102",
    taskId: "task-105",
    projectId: "preview-project",
    fileGroupId: "group-102",
    originalName: "archived-note.txt",
    mimeType: "text/plain",
    sizeBytes: 1204,
    storageBucket: "preview-bucket",
    objectPath: "preview/archived-note.txt",
    version: 1,
    versionNumber: 1,
    versionLabel: "v1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    uploadedBy: "preview-user",
    deletedAt: "2026-03-10T15:00:00.000Z",
    downloadUrl: null,
  },
];
